### ISSUE TITLE
Can you help me slove this problem

### ISSUE THREAD

**Issue by daring5920** [micahriggan/bitcore#18]
I were git pull for https://github.com/bitpay/bitcore/pull/2113

0|bit  | Unhandled Rejection at: Error: Invalid y value for curve.
0|bit  |     at Point.validate (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-lib/lib/crypto/point.js:123:11)
0|bit  |     at new PresetCurve (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-lib/node_modules/elliptic/lib/elliptic/curves.js:21:17)
0|bit  |     at Object.get [as p192] (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-lib/node_modules/elliptic/lib/elliptic/curves.js:31:19)
0|bit  |     at derez (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/cycle/cycle.js:93:47)
0|bit  |     at derez (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/cycle/cycle.js:93:36)
0|bit  |     at derez (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/cycle/cycle.js:93:36)
0|bit  |     at derez (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/cycle/cycle.js:93:36)
0|bit  |     at derez (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/cycle/cycle.js:93:36)
0|bit  |     at derez (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/cycle/cycle.js:84:29)
0|bit  |     at Object.decycle (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/cycle/cycle.js:101:6)
0|bit  |     at Object.exports.clone (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/winston/lib/winston/common.js:97:22)
0|bit  |     at Object.exports.log (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/winston/lib/winston/common.js:149:19)
0|bit  |     at exports.Console.Console.log (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/winston/lib/winston/transports/console.js:99:19)
0|bit  |     at transportLog (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/winston/lib/winston/logger.js:234:15)
0|bit  |     at /home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/winston/node_modules/async/lib/async.js:157:13
0|bit  |     at _each (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/winston/node_modules/async/lib/async.js:57:9)
0|bit  |     at Object.async.each (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/winston/node_modules/async/lib/async.js:156:9)
0|bit  |     at exports.Logger.Logger.log (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/winston/lib/winston/logger.js:246:9)
0|bit  |     at exports.Logger.target.(anonymous function) [as info] (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/winston/lib/winston/common.js:54:18)
0|bit  |     at P2pManager.start (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/build/src/services/p2p.js:61:26)
0|bit  |     at runMaster (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/build/src/server.js:20:15)
0|bit  |     at <anonymous>
0|bit  | info: Connected to btc peer 127.0.0.1 chain=BTC, network=regtest
0|bit  | error: Error: Timeout error: ping 172.16.0.57:30303
0|bit  |     at Timeout._onTimeout (/home/bitcore/bitcore-full-new/bitcore-full/packages/bitcore-node/node_modules/ethereumjs-devp2p/lib/dpt/server.js:97:29)
0|bit  |     at ontimeout (timers.js:498:11)
0|bit  |     at tryOnTimeout (timers.js:323:5)
0|bit  |     at Timer.listOnTimeout (timers.js:290:5)

**Comment by daring5920** [comment]
private chain id use mine
